# Generated by Django 4.0.6 on 2022-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_name',
            new_name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='p_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='p_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
