# Generated by Django 4.0.6 on 2022-07-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_doc_name_booking_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doctor_name',
            new_name='doc_name',
        ),
    ]
