# Generated by Django 4.0.6 on 2022-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hos_con_dept',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='hos_con_num',
            field=models.IntegerField(null=True),
        ),
    ]
