# Generated by Django 4.0.6 on 2022-07-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_hos_con_dept_contact_hos_con_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='hos_con_dept',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
